/*! Generated by script */
void PieModel::setStartAngle (qreal startAngle)
{
    if (_startAngle != startAngle) {
	_startAngle = startAngle;
	emit startAngleChanged(startAngle);
    }
}

/*! Generated by script */
qreal PieModel::startAngle () const
{
    return _startAngle;
}

