#include "piemodel.h"

PieModel::PieModel(QObject *parent) :
    QObject(parent),
    _startAngle(0),
    _endAngle(0)
{
}

PieModel::~PieModel()
{
}

/*! Generated by script */
void PieModel::setStartangle (qreal startAngle)
{
    if (_startAngle != startAngle) {
	_startAngle = startAngle;
	emit startAngleChanged(startAngle);
    }
}

/*! Generated by script */
qreal PieModel::startAngle () const
{
    return startAngle;
}

/*! Generated by script */
void PieModel::setEndangle (qreal endAngle)
{
    if (_endAngle != endAngle) {
	_endAngle = endAngle;
	emit endAngleChanged(endAngle);
    }
}

/*! Generated by script */
qreal PieModel::endAngle () const
{
    return endAngle;
}

/*! Generated by script */
void PieModel::setName (const QString & name)
{
    if (_name != name) {
	_name = name;
	emit nameChanged(name);
    }
}

/*! Generated by script */
const QString & PieModel::name () const
{
    return name;
}

/*! Generated by script */
void PieModel::setDetail (const QString & detail)
{
    if (_detail != detail) {
	_detail = detail;
	emit detailChanged(detail);
    }
}

/*! Generated by script */
const QString & PieModel::detail () const
{
    return detail;
}

