######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 8 22:31:16 2011
######################################################################

QT -= gui core
TEMPLATE = lib
TARGET = swe
DEPENDPATH += . src include
INCLUDEPATH += . src include

# Input
include (libswe.pri)
