#include "styleoption.h"

StyleOption::StyleOption(QObject *parent) :
    QObject(parent)
{
}
/*! Generated by script */
void StyleOption::setBrush (const QBrush & brush)
{
    if (_brush != brush) {
	_brush = brush;
	emit brushChanged(brush);
    }
}

/*! Generated by script */
const QBrush & StyleOption::brush () const
{
    return _brush;
}

/*! Generated by script */
void StyleOption::setPen (const QPen & pen)
{
    if (_pen != pen) {
	_pen = pen;
	emit penChanged(pen);
    }
}

/*! Generated by script */
const QPen & StyleOption::pen () const
{
    return _pen;
}

/*! Generated by script */
void StyleOption::setFont (const QFont & font)
{
    if (_font != font) {
	_font = font;
	emit fontChanged(font);
    }
}

/*! Generated by script */
const QFont & StyleOption::font () const
{
    return _font;
}

